### ISSUE TITLE
Stop using machine in favor of microcontroller.

### ISSUE THREAD

**Issue by tannewt** [adafruit/micropython#22]
MicroPython's `machine` module varies a lot between different ports. Instead, we should define a separate API `microcontroller` in `shared-bindings` that ensures identical APIs by sharing code. It should be divided into three submodules:
- `microcontroller.core` Processor related functionality such as sleep states.
- `microcontroller.pin` Microcontroller level pin definitions such as PA13. Board names should live elsewhere. (In a separate `board` for example.)
- `microcontroller.peripheral` Provides classes for common hardware peripherals such as GPIO, I2C, SPI, Timers, UART, DAC and ADC.

**Comment by deshipu** [comment]
https://imgs.xkcd.com/comics/standards.png

**Comment by tannewt** [comment]
`microcontroller`, `nativeio` and `board` have been added in place of `machine`.
