### ISSUE TITLE
SamD21E18 SD card support

### ISSUE THREAD

**Issue by bobricius** [adafruit/micropython#30]
Hi, I understand that this is Adafruit business, But I want ask for help, or maybe somebody can push small branch for this MCU. I think that it need only small changes just add another SPI and add a27, a28 to pins.
I using this binaries on my board without changes, All works but in E variant missing pins for SPI = SD card not working
My connection is: (like uno D11,D12,D13)
miso a19
mosi a16
sck a17
ss a18

Onboard RGB led is connected to a19, a17, a27
Onboard user button is connected to a28

I have no money to pay development but I can offer free board for testing and as a reward.
Details about WINXI project [Hackaday.io](https://hackaday.io/project/10208-winxi-arduino-zero-pro-m0-stick-atsamd21e18)

**Comment by tdicola** [comment]
Thanks for the offer but lets keep issues to just problems with the code in this repo, not requests for help, etc.  Check out the Adafruit forums and jobs board for good places to see if other folks can help with a project.  Good luck!
