### ISSUE TITLE
mac OS displays free space as MB and set creation time to more appropriate date

### ISSUE THREAD

**Issue by ptorrone** [adafruit/micropython#34]
on a mac (os 10.11.6) metro express will show up with 48KB, 39.3 MB free. also, the time volume (partition create time/date) is "Wednesday, December 31, 1969 at 7:00 PM" ... we could pick a more appropriate date.

running - 1.8.5-20161020 on 2016-10-20 Adafruit Feather M0 Basic with samd21g18

image attached.

![img](https://cloud.githubusercontent.com/assets/1685947/19622337/aa5d0002-9875-11e6-8a0e-8beb026e2270.png)

**Comment by tannewt** [comment]
File size is now correct. I'm not going to change creation time because we're going to format the fs externally rather than using MicroPython to do it.
