### ISSUE TITLE
need a spi flash formatter

### ISSUE THREAD

**Issue by ptorrone** [adafruit/micropython#40]
hi hi! need a spi flash formatter to start over with a clean file system in case something goes really wrong (testing on macs with autosaving on for text edit for example!)

**Comment by tannewt** [comment]
Plan is that for internal flash, provide two binaries, one without the flash system and one with it.

For external flash, the bootloader is responsible for keeping the flash FS valid.

**Comment by tannewt** [comment]
Look into Etcher for reflashing the spi flash.

**Comment by tannewt** [comment]
I'm gonna take this off the milestones because some firmware flashing stuff may make this unnecessary.

**Comment by tannewt** [comment]
We can provide a separate binary people can flash to format it if they can't do it directly over mass storage.
