### ISSUE TITLE
NeoPixel module enhancements

### ISSUE THREAD

**Issue by tdicola** [adafruit/micropython#48]
Right now the neopixel modules supports GRB order 400khz and 800khz pixel strips.  We should update the module to support a wider range of pixel types:
- RGB and other arbitrary byte orders
- RGBW strips

This can probably all be done in the Python module as the low level pixel write function just takes an array of bytes to send out to the pixels (so it can change from 3-tuples to 4-tuples of color info for RGBW easily).

**Comment by tannewt** [comment]
Moved to https://github.com/adafruit/Adafruit_MicroPython_NeoPixel/issues/1
