### ISSUE TITLE
atmel-samd: Can't save to drive from Mac's built in text editor

### ISSUE THREAD

**Issue by tdicola** [adafruit/micropython#52]
Trying to save a main.py on the board's mass storage drive I get an error from the built in text editor that the drive can't be found or the file can't be saved:
<img width="617" alt="screen shot 2016-11-11 at 12 35 52 pm" src="https://cloud.githubusercontent.com/assets/1332183/20229513/c05f9cfc-a80b-11e6-97c2-c527d026e105.png">

PT & Pedro have noticed this too.  Perhaps something is up with the drive and how text edit expects the filesystem, etc. to work.  Needs a bit more investigation.

**Comment by willingc** [comment]
@tdicola Is this possibly a SD formatting issue?

**Comment by tannewt** [comment]
I think this was fixed as part of ccbb5e84f980e252f7380d96fcc5c417a8a64523. There was a bug where the ram cache got deleted by the gc and then a write to flash was attempted from it. Another bug squashed was an infinite loop when failing to allocate the ram cache.
