### ISSUE TITLE
Some GPIO not accessible 

### ISSUE THREAD

**Issue by bobricius** [adafruit/micropython#54]
Hi, some special ZERO GPIO are not accessible.

etc
 * | 25         |                  |  PB03  | RX
 * | 26         |                  |  PA27  | TX 
 * | 27         |                  |  PA28  | USB_HOST_ENABLE
 * | 42         | AREF         |  PA03  | 
 * | 30         |                  |  PB22  | EDBG_UART TX 
 * | 31         |                  |  PB23  | EDBG_UART RX
 * | 32         |                  |  PA22  | EDBG_SDA
 * | 33         |                  |  PA23  | EDBG_SCL

**Comment by tannewt** [comment]
What port and what version (commit)? I can look tomorrow.

**Comment by bobricius** [comment]
etc now ... micropython/atmel-samd/boards/arduino_zero/pins.c

This pins are not defined and maybe more, compared to arduino samd core variant
I understand that this pins are usually not used.

**Comment by tannewt** [comment]
The pins should be available through their microcontroller names such as PA22 from the `microcontroller.pin` module. That module's pins are done automatically based on defines. https://github.com/adafruit/micropython/blob/master/atmel-samd/common-hal/microcontroller/__init__.c#L148

**Comment by tannewt** [comment]
Having these accessible through `microntroller.pin` is enough to me.
