### ISSUE TITLE
blinly example not working

### ISSUE THREAD

**Issue by g-ollivier** [adafruit/micropython#55]
Hello,
I pulled the whole project, rebuilt the image and flashed a feather_m0_basic (as of Nov 24th).
Then I tried the blinky example as in http://tannewt-micropython.readthedocs.io/en/microcontroller/shared-bindings/nativeio/__init__.html
And I get an error : OSError: Cannot set value when direction is input

I have to add a led.switch_to_output() before led.value = True in order to make it work.

Since we have to set the direction (output or input), would it be easier to have the same approach as you made with AnalogIn and AnalogOut ?

**Comment by tannewt** [comment]
Oh yeah. That example is definitely wrong. Its missing a loop too.

We were thinking of adding a helper set of classes, DigitalIn and
DigitalOut to wrap around DigitalInOut to make it easier.

For now, I'll fix up the example on Monday after this long weekend in the
US.

Thanks for the report!
