### ISSUE TITLE
atmel-samd: Filesystem out of free space when copying over empty files.

### ISSUE THREAD

**Issue by tdicola** [adafruit/micropython#67]
I noticed something odd using the samd21 port on Feather M0 basic, it seems like empty files (and perhaps even files below 4k in size) are counting as larger size files.  I can only copy over 10 0 byte files before I receive an out of free space error.

Version:
```
Adafruit CircuitPython v1.8.6-187-g3986870-dirty on 2016-12-21; Adafruit Feather M0 Basic with samd21g18
```

Repro steps:
- Flash firmware above (latest build) to ensure filesystem is empty.
- Create a bunch of zero byte files, like:
  ```
  touch empty_file_1.txt
  touch empty_file_2.txt
  etc...
  ```
- Attempt to drag a large number of empty files (20) to the board in OSX finder.  Notice the copy fails after 10 files:
  <img width="767" alt="screen shot 2017-01-02 at 8 55 31 pm" src="https://cloud.githubusercontent.com/assets/1332183/21600300/9b0e6dc4-d12e-11e6-8c47-2019dde85ad5.png">

**Comment by tdicola** [comment]
Interestingly the uos.stat command sees the files as 0 bytes (the 4th to last tuple entry, a 0 below):
```
>>> uos.stat('empty_file_8.txt')
(32768, 0, 0, 0, 0, 0, 0, 536706658, 536706658, 536706658)
```
But trying to copy more files over still results in an out of space error in OSX finder.

**Comment by tannewt** [comment]
Can you copy more files over if some of them are in a directory? You can
fill up a file system with empty files because of the overhead. I'm
surprised its happening at ten files though.

**Comment by tannewt** [comment]
Copying via command line works fine. Mac OS X is notorious for lots of spare files so it looks unique to Finder. Nothing on the MicroPython side we can do about it.
