### ISSUE TITLE
Add new USB PID for Feather M0 with CDC + MSC

### ISSUE THREAD

**Issue by tdicola** [adafruit/micropython#8]
Right now the feather M0 bluefruit uses the USB PID 0x000b.  This is the same as the bootloader PID though and can cause some confusion.  Talking to Limor we really want a new PID for this since it's a new 'class' of device with CDC + MSC (vs. just CDC alone that would be PID 0x800b).

**Comment by tannewt** [comment]
Fixed in 90bf13e
